# Sample configuration file for Sidekiq.
# Options here can still be overridden by cmd line args.
# Place this file at config/sidekiq.yml and Sidekiq will
# pick it up automatically.
---
:verbose: false
:concurrency: 10
:timeout: 25

:queues:
  - test
  - entry
  - low

# you can override concurrency based on environment
production:
  :concurrency: 25
staging:
  :concurrency: 15
development:
  :concurrency: 15
